queue_rules:
  - name: default
    conditions:
      - check-success=build (3.8)
      - check-success=build (3.9)
      - check-success=build (3.10)

pull_request_rules:
  - name: dependabot
    actions:
      queue:
        method: rebase
        name: default
    conditions:
    - author=dependabot[bot]
    - label!=no-mergify
    - "#changes-requested-reviews-by=0"
    - check-success=build (3.8)
    - check-success=build (3.9)
    - check-success=build (3.10)

  - name: default
    actions:
      queue:
        method: rebase
        name: default
    conditions:
    - label!=no-mergify
    - '#approved-reviews-by>=1'
    - check-success=build (3.8)
    - check-success=build (3.9)
    - check-success=build (3.10)
